
local VIEWDEFS = {}

VIEWDEFS.VIEWPORT_WIDTH_SCALE = 0.75
VIEWDEFS.PANEL_MG = 24
VIEWDEFS.TILE_W = 80
VIEWDEFS.TILE_H = 60
VIEWDEFS.HALF_W = 9
VIEWDEFS.HALF_H = 7

function VIEWDEFS.VIEWPORT_DIMENSIONS()
  local W,H = love.graphics.getDimensions()
  W = W * VIEWDEFS.VIEWPORT_WIDTH_SCALE
  return W, H
end

return VIEWDEFS

