
-- luacheck: globals love

local VIEWDEFS = {}

VIEWDEFS.VIEWPORT_WIDTH_SCALE = 1
VIEWDEFS.PANEL_MG = 24
VIEWDEFS.PANEL_W  = 320
VIEWDEFS.PANEL_H  = 180
VIEWDEFS.ROWS   = 12
VIEWDEFS.COLS   = 16
VIEWDEFS.TILE_W = 80
VIEWDEFS.TILE_H = 60
VIEWDEFS.HALF_W = 9
VIEWDEFS.HALF_H = 7
VIEWDEFS.CARD_W = 72
VIEWDEFS.CARD_H = 120
VIEWDEFS.CARD_COND_SCALE_X = .64
VIEWDEFS.CARD_COND_SCALE_Y = .40

function VIEWDEFS.VIEWPORT_DIMENSIONS()
  local W,H = love.graphics.getDimensions()
  W = W * VIEWDEFS.VIEWPORT_WIDTH_SCALE
  return W, H
end

return VIEWDEFS
